ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_LOGIN_SUCCEEDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_REFRESH_ROTATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_LOGOUT';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_REFRESH_REUSE_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_USER_SOFT_DELETED';
