export const ADMIN_ROLES = ["SUPER_ADMIN", "ADMIN", "MODERATOR", "SUPPORT"] as const;
export type AdminRole = (typeof ADMIN_ROLES)[number];

export const PERMISSIONS = {
  DASHBOARD_READ: "dashboard.read",
  ADMIN_MANAGE: "admin.manage",
  SCHOLARSHIP_APPROVE: "scholarship.approve",
  SCHOLARSHIP_WRITE: "scholarship.write",
  USER_READ: "user.read",
  USER_SUSPEND: "user.suspend",
  USER_DELETE: "user.delete",
  ORGANIZATION_READ: "organization.read",
  ORGANIZATION_REVIEW: "organization.review",
  APPLICATION_READ: "application.read",
  APPLICATION_REVIEW: "application.review",
  SETTINGS_WRITE: "settings.write",
  CONSULTING_REPLY: "consulting.reply",
  CONTENT_MANAGE: "content.manage",
  NOTIFICATION_READ: "notification.read",
  TRASH_MANAGE: "trash.manage",
  SYSTEM_READ: "system.read",
  REPORT_MANAGE: "report.manage",
  AUDIT_READ: "audit.read",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<AdminRole, readonly Permission[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.SCHOLARSHIP_APPROVE, PERMISSIONS.SCHOLARSHIP_WRITE, PERMISSIONS.USER_READ, PERMISSIONS.USER_SUSPEND, PERMISSIONS.USER_DELETE, PERMISSIONS.ORGANIZATION_READ, PERMISSIONS.ORGANIZATION_REVIEW, PERMISSIONS.APPLICATION_READ, PERMISSIONS.APPLICATION_REVIEW, PERMISSIONS.SETTINGS_WRITE, PERMISSIONS.CONSULTING_REPLY, PERMISSIONS.CONTENT_MANAGE, PERMISSIONS.NOTIFICATION_READ, PERMISSIONS.TRASH_MANAGE, PERMISSIONS.SYSTEM_READ, PERMISSIONS.REPORT_MANAGE, PERMISSIONS.AUDIT_READ],
  MODERATOR: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.SCHOLARSHIP_APPROVE, PERMISSIONS.SCHOLARSHIP_WRITE, PERMISSIONS.ORGANIZATION_READ, PERMISSIONS.ORGANIZATION_REVIEW],
  SUPPORT: [PERMISSIONS.DASHBOARD_READ, PERMISSIONS.USER_READ, PERMISSIONS.APPLICATION_READ, PERMISSIONS.CONSULTING_REPLY, PERMISSIONS.NOTIFICATION_READ],
};

export function hasPermission(role: string, permission: Permission) {
  return ADMIN_ROLES.includes(role as AdminRole) && ROLE_PERMISSIONS[role as AdminRole].includes(permission);
}
